language: python

python:
  - "2.7"
  - "3.5"

sudo: false

cache:
  - apt
  - pip

install:
  - pip install -r requirements.txt -r requirements-dev.txt

script: python -m unittest discover src

branches:
  only:
    - develop
    - master
