language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

sudo: false

cache:
  - apt
  - pip

install:
  - pip install -r requirements-dev.txt
  - pip install -e .

script: coverage run --source=pascal_templates --module unittest discover src

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - develop
    - master

